---
# description: RedHat specific installation
- name: "Installation - Add yum repository"
  yum_repository:
    name: klaytn
    description: Klaytn Package Repository
    baseurl: http://packages.klaytn.net/rhel/7/prod/
    gpgcheck: no
  become: yes
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: "Installation - Install Klaytn Package "
  yum:
    name: '{{ klaytn_service_type }}'          
    state: latest
  register: is_klaytn_package_installed
  until: is_klaytn_package_installed is succeeded
  become: yes
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: "Installation - Download Klaytn Package"
  get_url:
    url: "https://packages.klaytn_net/klaytn/{{ klaytn_homi.version }}/{{ klaytn_service_type | regex_replace ('d') }}-{{ klaytn_homi.version }}-0-linux-amd64.tar.gz"
    dest: "{{ klaytn_node_DATA_DIR }}/{{ klaytn_service_type }}.tar.gz"
    mode: "0755"
  become: yes
  when: ansible_facts['pkg_mgr'] != 'yum'

- name: "Installation - Unarchive Klaytn Package"
  unarchive:
    src: "{{ klaytn_node_DATA_DIR }}/{{ klaytn_service_type }}.tar.gz"
    dest: "{{ klaytn_node_DATA_DIR }}"
    remote_src: yes
  become: yes
  register: extract_result
  when: ansible_facts['pkg_mgr'] != 'yum'

- name: "Installation - Make Config Directory if not exists"
  file:
    path: "/etc/{{ klaytn_service_type }}/conf"
    state: "directory"
  become: yes
  when: ansible_facts['pkg_mgr'] != 'yum'

- name: "Installation - Move Unarchived Files into Proper Path"
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: yes 
  with_items: 
    - { "src": "{{ klaytn_service_type | regex_replace ('d') }}-linux-amd64/bin/{{ klaytn_service_type | regex_replace ('d') }}", "dest": "/usr/bin/{{ klaytn_service_type | regex_replace ('d') }}" }
    - { "src": "{{ klaytn_service_type | regex_replace ('d') }}-linux-amd64/conf/{{ klaytn_service_type }}.conf", "dest": "/etc/{{ klaytn_service_type }}/conf/{{ klaytn_service_type }}.conf" }
  when: ansible_facts['pkg_mgr'] != 'yum'

  
