---
# description: Klaytn Configuration
- name: "Make configuration directory"
  file:
    path: "/opt/{{ klaytn_service_type }}/conf"
    state: "directory"
  become: yes
  when: ansible_facts['pkg_mgr'] != 'yum'

- name: "Make configuration directory"
  file:
    path: "/etc/{{ klaytn_service_type }}/conf"
    state: "directory"
  become: yes
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: "Klaytn Configuration"
  template:
    src: "{{ klaytn_service_type }}.conf.j2"
    dest: "/opt/{{ klaytn_service_type }}/conf/{{ klaytn_service_type }}.conf"
  become: yes
  when: ansible_facts['pkg_mgr'] != 'yum'

- name: "Klaytn Configuration"
  template:
    src: "{{ klaytn_service_type }}.conf.j2"
    dest: "/etc/{{ klaytn_service_type }}/conf/{{ klaytn_service_type }}.conf"
  become: yes
  when: ansible_facts['pkg_mgr'] == 'yum'
